"""Regenerate the committed example export at ``docs/examples/example-packet.md``.

Runs the SAME offline path the app's guided demo walks (ADR-025/ADR-026): the
bundled SYNTHETIC Radar handoff, the bundled SYNTHETIC contract-facts sample,
the bundled SYNTHETIC PL Services workbook, the bundled SYNTHETIC NIB/NPA
directory workbook, and an analyst-entered staffing baseline. No network call
is made and no fact is typed here -- the document is assembled by the same
``build_opportunity_packet_markdown`` / ``derive_section_ledger`` /
``derive_source_manifest`` / ``assemble_packet_export`` chain that
``bd_page._render_opportunity_packet`` calls (bd_page.py:1284-1350).

The live pulls (ACS geography, USAspending subawards, Federal Register PL
notices) are deliberately NOT attached: they need a network and, for ACS, an
API key. The packet's honest-absence behavior is part of what the example is
meant to show.

``as_of`` is fixed so the output is byte-stable across runs; regenerate with:

    py -m pip install -r requirements-dev.txt   # openpyxl parses the workbooks
    py scripts/generate_example_packet.py
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "src"))

from tens_hq.connectors import (  # noqa: E402
    AbilityOneServicesConnector,
    NIBNPAConnector,
    load_synthetic_example_facts,
)
from tens_hq.opportunity_packet import build_opportunity_packet_markdown  # noqa: E402
from tens_hq.packet_export import (  # noqa: E402
    assemble_packet_export,
    derive_section_ledger,
    derive_source_manifest,
)
from tens_hq.pl_match import find_pl_service_matches  # noqa: E402
from tens_hq.radar_handoff import parse_radar_handoff  # noqa: E402
from tens_hq.staffing_whatif import (  # noqa: E402
    StaffingWhatIfInput,
    WhatIfMode,
    assess_staffing_whatif,
)

_SAMPLES = _REPO_ROOT / "data" / "samples"
_OUT_PATH = _REPO_ROOT / "docs" / "examples" / "example-packet.md"

# Fixed so the committed artifact is byte-stable across regenerations.
_AS_OF = datetime(2026, 7, 24, 12, 0, 0, tzinfo=timezone.utc)

_HANDOFF_LABEL = "sample_radar_handoff.json (SYNTHETIC example)"
_PL_LABEL = "sample_pl_services.xlsx (SYNTHETIC example)"
_DIRECTORY_LABEL = "sample_nib_npa.xlsx (SYNTHETIC example)"

_PREAMBLE = """<!-- Generated by scripts/generate_example_packet.py. Do not hand-edit. -->
# Example export — Opportunity Packet

This file is the real, unedited output of ReconRadar's export path, generated
offline from the repository's own bundled SYNTHETIC samples by
`scripts/generate_example_packet.py`. Every value below came out of the code;
none of it was typed by hand.

Everything in it is SYNTHETIC and labeled as such. The ACS geography, subaward,
and Federal Register sections are absent because those are live pulls that this
offline run did not make — the Section ledger at the bottom says so, by name,
with the reason. That is the point of the ledger.

---

"""


def main() -> int:
    handoff = parse_radar_handoff((_SAMPLES / "sample_radar_handoff.json").read_bytes())
    resolution = load_synthetic_example_facts()
    contract_facts = resolution.record
    if contract_facts is None:  # pragma: no cover - the bundled sample always resolves
        raise SystemExit("bundled synthetic contract-facts sample failed to resolve")

    pl_records = AbilityOneServicesConnector().parse(
        (_SAMPLES / "sample_pl_services.xlsx").read_bytes()
    ).records
    pl_matches = find_pl_service_matches(
        pl_records,
        city="Denver",
        state="CO",
        service_type=None,
        source_label=_PL_LABEL,
        retrieved_at="2026-07-24",
        synthetic_sample=True,
    )

    directory_records = NIBNPAConnector().parse(
        (_SAMPLES / "sample_nib_npa.xlsx").read_bytes()
    ).records
    directory_agency_names = [
        name for record in directory_records if (name := record.get("agency_name"))
    ]

    staffing = assess_staffing_whatif(
        StaffingWhatIfInput(
            mode=WhatIfMode.HOURS,
            baseline_qualifying_hours=78000.0,
            baseline_total_hours=120000.0,
            scenario_total_hours=20000.0,
            scenario_qualifying_share=0.75,
        )
    )

    piid = contract_facts.piid or ""
    county = "Denver"
    state = "CO"

    body = build_opportunity_packet_markdown(
        piid=piid,
        county=county,
        state=state,
        eligibility=None,
        geography=None,
        pl_matches=pl_matches,
        pl_notices=None,
        contract_facts=contract_facts,
        subawards=None,
        directory_agency_names=directory_agency_names,
        radar_handoff=handoff,
        staffing=staffing,
        as_of=_AS_OF,
    )
    ledger = derive_section_ledger(
        eligibility=None,
        contract_facts=contract_facts,
        geography=None,
        pl_matches=pl_matches,
        subawards=None,
        directory_agency_names=directory_agency_names,
        handoff_attached=True,
        handoff_piid_matched=True,
        staffing=staffing,
        pl_notices=None,
    )
    manifest = derive_source_manifest(
        contract_facts=contract_facts,
        subawards=None,
        geography=None,
        pl_matches=pl_matches,
        directory_source_label=_DIRECTORY_LABEL,
        set_aside_analyst_value=None,
        handoff=handoff,
        handoff_source_label=_HANDOFF_LABEL,
        handoff_piid_matched=True,
        staffing=staffing,
        pl_notices=None,
    )
    export_doc = assemble_packet_export(
        body_markdown=body,
        piid=piid,
        county=county,
        state=state,
        ledger=ledger,
        manifest=manifest,
        as_of=_AS_OF,
    )

    _OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUT_PATH.write_text(_PREAMBLE + export_doc, encoding="utf-8", newline="\n")
    print(f"wrote {_OUT_PATH.relative_to(_REPO_ROOT)} ({len(export_doc.splitlines())} export lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
