"""Generate a SYNTHETIC sample NIB/NPA directory workbook for the demo.

This writes ``data/samples/sample_nib_npa.xlsx`` -- a tiny, clearly-labeled
EXAMPLE workbook the tracker's public-evidence scan can load for the
``NIB_NPA`` source kind so a stranger can drive the Scan -> Validated
readiness lifecycle offline. It is **not** the official NIB/SourceAmerica
nonprofit-agency directory; every row is invented and the file carries an
explicit synthetic-marker title row.

Run once and commit the artifact:

    py scripts/make_sample_nib_npa.py

The generated bytes are NOT byte-stable across runs (the zip stamps each
member with the current time), so do not add a "regenerate and diff" check.
The rows below are the source of truth; regenerate only when they change.

Rows are Denver, CO to line up with the bundled radar handoff and the
bundled PL Services sample, so the same worksite city exercises both
evidence lanes offline.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

# Schema headers for SourceKind.NIB_NPA (connectors/abilityone.py:50-55).
HEADERS = ["Nonprofit Agency Name", "City", "State", "Zip Code"]

TITLE = (
    "SYNTHETIC EXAMPLE - not a real NIB/SourceAmerica directory "
    "(illustrative demo data only)"
)

ROWS: list[list[str]] = [
    ["Mile High Community Workshop", "Denver", "CO", "80202"],
    ["Front Range Ability Partners", "Denver", "CO", "80204"],
    ["Rocky Mountain Vocational Services", "Aurora", "CO", "80010"],
]


def _col(index: int) -> str:
    result = ""
    index += 1
    while index:
        index, rem = divmod(index - 1, 26)
        result = chr(65 + rem) + result
    return result


def build_workbook(title: str, headers: list[str], rows: list[list[str]]) -> bytes:
    xml_rows: list[str] = []
    for row_number, values in enumerate([[title], headers] + rows, 1):
        cells = []
        for index, value in enumerate(values):
            text = "" if value is None else str(value)
            cells.append(f'<c r="{_col(index)}{row_number}" t="inlineStr"><is><t>{text}</t></is></c>')
        xml_rows.append(f'<row r="{row_number}">' + "".join(cells) + "</row>")
    sheet = (
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        "<sheetData>" + "".join(xml_rows) + "</sheetData></worksheet>"
    )
    workbook_xml = (
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets><sheet name="Directory" sheetId="1" r:id="rId1"/></sheets></workbook>'
    )
    rels = (
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
        'Target="worksheets/sheet1.xml"/></Relationships>'
    )
    types = (
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="xml" ContentType="application/xml"/></Types>'
    )
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", types)
        archive.writestr("xl/workbook.xml", workbook_xml)
        archive.writestr("xl/_rels/workbook.xml.rels", rels)
        archive.writestr("xl/worksheets/sheet1.xml", sheet)
    return output.getvalue()


def main() -> None:
    target = Path(__file__).resolve().parent.parent / "data" / "samples" / "sample_nib_npa.xlsx"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(build_workbook(TITLE, HEADERS, ROWS))
    print(f"Wrote {target} ({target.stat().st_size} bytes, {len(ROWS)} rows).")


if __name__ == "__main__":
    main()
